import java.util.Random;
import java.util.Scanner;

public class RandomNumber {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        Random random = new Random();

        int number = random.nextInt(100); // 0 to 99
        System.out.println("Computer's number is: " + number); // checking line to see the number generated by the computer.

        int guess;

        System.out.println("Guess the number between 0 and 99:");

        // for loop used as an infinite loop
        for (;;) {
            guess = scanner.nextInt();

            if (guess > number) {
                System.out.println("Too High!");
            }
            else if (guess < number) {
                System.out.println("Too Low!");
            }
            else {
                System.out.println("Correct!");
                break; // exit loop when correct
            }
        }

        scanner.close();
    }
}

